@include('layouts.backend.navigation.html.analysis')
@include('layouts.backend.navigation.html.monitoring')
@include('layouts.backend.navigation.html.province')
@include('layouts.backend.navigation.html.dho')
@include('layouts.backend.navigation.html.municipality')
@include('layouts.backend.navigation.html.organization')
@include('layouts.backend.navigation.html.cases-payment')
@include('layouts.backend.navigation.html.map')