{{-- @include('layouts.backend.navigation.html.analysis') --}}
@include('layouts.backend.navigation.html.center')
@include('layouts.backend.navigation.html.province')
@include('layouts.backend.navigation.html.dho')
@include('layouts.backend.navigation.html.municipality')
@include('layouts.backend.navigation.html.organization')
@include('layouts.backend.navigation.html.cases-payment')
@include('layouts.backend.navigation.html.cases-report')
@include('layouts.backend.navigation.html.swab')
@include('layouts.backend.navigation.html.map')
@include('layouts.backend.navigation.html.notice')
@include('layouts.backend.navigation.html.user-manager')