@include('layouts.backend.navigation.html.dho')
@include('layouts.backend.navigation.html.municipality')
@include('layouts.backend.navigation.html.organization')
@include('layouts.backend.navigation.html.lab-users')
@include('layouts.backend.navigation.html.cases-payment')
@include('layouts.backend.navigation.html.swab')
