@include('layouts.backend.navigation.html.dho')
@include('layouts.backend.navigation.html.municipality')
@include('layouts.backend.navigation.html.organization')
@include('layouts.backend.navigation.html.lab-users')
@include('layouts.backend.navigation.html.active-cases')
@include('layouts.backend.navigation.html.close-cases')
@include('layouts.backend.navigation.html.case-result-report')
@include('layouts.backend.navigation.html.cases-payment')
@include('layouts.backend.navigation.html.swab')

